import { JSDOM } from 'jsdom';
const dom = new JSDOM('<!doctype html><html><body><div id="root"></div></body></html>', { url: 'http://localhost/motivaciya/', pretendToBeVisual: true });
const w = dom.window as unknown as Record<string, unknown>;
for (const k of ['window', 'document', 'navigator', 'localStorage', 'HTMLElement', 'HTMLInputElement', 'Node', 'Event', 'KeyboardEvent', 'FocusEvent', 'TouchEvent', 'MouseEvent', 'getComputedStyle', 'requestAnimationFrame', 'cancelAnimationFrame']) (globalThis as Record<string, unknown>)[k] = w[k];
(globalThis as Record<string, unknown>).matchMedia = () => ({ matches: false, addEventListener() {}, removeEventListener() {} });
(w as Record<string, unknown>).matchMedia = (globalThis as Record<string, unknown>).matchMedia;
(globalThis as Record<string, unknown>).ResizeObserver = class { observe() {} disconnect() {} unobserve() {} };
(w as Record<string, unknown>).ResizeObserver = (globalThis as Record<string, unknown>).ResizeObserver;
(globalThis as Record<string, unknown>).IS_REACT_ACT_ENVIRONMENT = true;
(globalThis as Record<string, unknown>).fetch = async () => { throw new Error('offline-test'); };
const { default: React, act } = await import('react');
const { createRoot } = await import('react-dom/client');
const { default: App } = await import('../src/App');
const el = document.getElementById('root')!; const root = createRoot(el);
await act(async () => { root.render(React.createElement(App)); });
await act(async () => { await new Promise((r) => setTimeout(r, 50)); });
const btn = Array.from(document.querySelectorAll('button')).find((b) => b.textContent?.includes('Как установить приложение?'));
console.log('btn', !!btn);
await act(async () => { btn!.dispatchEvent(new (window as any).MouseEvent('click', { bubbles: true })); });
const b = document.body.innerHTML;
console.log('modal?', b.includes('role="dialog"'), 'len', b.length);
const i = b.indexOf('Выберите устройство'); console.log(b.slice(i, i + 1500).replace(/<[^>]+>/g, '|').replace(/\|+/g, '|'));
